import { useState } from "react";
import Navigation from "@/components/Navigation";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getLocalChatbotReply } from "@/lib/chatbotLocal";

type ChatMessage = {
  id: string;
  from: "user" | "bot";
  text: string;
};

const ChatbotPage = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "welcome",
      from: "bot",
      text: "Hi! I’m your pillbox assistant. Ask me about reminders, notifications, ESP32 setup, or how to use the app.",
    },
  ]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = input.trim();
    if (!trimmed || sending) return;

    const userMessage: ChatMessage = {
      id: `user_${Date.now()}`,
      from: "user",
      text: trimmed,
    };

    setSending(true);

    const localAnswer = getLocalChatbotReply(trimmed);
    const localMessage: ChatMessage = {
      id: `bot_local_${Date.now()}`,
      from: "bot",
      text: localAnswer.reply,
    };

    setMessages((prev) => [...prev, userMessage, localMessage]);
    setInput("");

    const resolveDefaultApiUrl = () => {
      let url = "http://localhost:3001/chat";
      try {
        const platform = (window as any)?.Capacitor?.getPlatform?.();
        if (platform === "android") {
          url = "http://10.0.2.2:3001/chat";
        }
      } catch {
        // ignore
      }
      return url;
    };

    const configuredApi = import.meta.env.VITE_CHAT_API_URL?.trim();
    const apiUrl = configuredApi || resolveDefaultApiUrl();

    if (configuredApi) {
      try {
        const controller = new AbortController();
        const timeoutId = window.setTimeout(() => controller.abort(), 10000);

        const res = await fetch(apiUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ message: trimmed }),
          signal: controller.signal,
        });

        window.clearTimeout(timeoutId);

        if (!res.ok) {
          throw new Error("Bad response");
        }

        const data: { reply?: string } = await res.json();
        if (data.reply) {
          const botMessage: ChatMessage = {
            id: `bot_cloud_${Date.now()}`,
            from: "bot",
            text: `${data.reply}\n\n(Generated by online assistant)`,
          };

          setMessages((prev) => [...prev, botMessage]);
        }
      } catch {
        // Ignore – local answer already shown
      } finally {
        setSending(false);
      }
    } else {
      setSending(false);
    }
  };

  return (
    <div className="min-h-screen bg-background pb-20 flex flex-col">
      <header className="bg-primary text-primary-foreground p-6 shadow-md">
        <h1 className="text-2xl font-bold mb-1">Pillbox Assistant</h1>
        <p className="text-sm opacity-90">
          Ask questions about reminders, medications & ESP32 setup
        </p>
      </header>

      <main className="flex-1 max-w-lg mx-auto w-full p-4 flex flex-col gap-4">
        <Card className="flex-1 p-4 flex flex-col gap-3 overflow-hidden">
          <div className="flex-1 overflow-y-auto space-y-3 pr-1">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex ${msg.from === "user" ? "justify-end" : "justify-start"}`}
              >
                <div
                  className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm ${
                    msg.from === "user"
                      ? "bg-primary text-primary-foreground rounded-br-sm"
                      : "bg-muted text-foreground rounded-bl-sm"
                  }`}
                >
                  {msg.text}
                </div>
              </div>
            ))}
          </div>

          <form onSubmit={handleSend} className="pt-2 border-t border-border space-y-2">
            <Label htmlFor="chat-input" className="text-xs text-muted-foreground">
              Ask something like “How do I add a reminder?” or “What are common side effects of this tablet?”
            </Label>
            <div className="flex gap-2">
              <Input
                id="chat-input"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Type your question..."
                autoComplete="off"
              />
              <Button type="submit" disabled={sending || !input.trim()}>
                Send
              </Button>
            </div>
          </form>
        </Card>

        <p className="text-[11px] text-muted-foreground leading-snug">
          This assistant gives only general information about medicines and health.
          It does not provide medical advice, diagnosis, or treatment. Always
          consult a qualified doctor or pharmacist for decisions about your health.
        </p>
      </main>

      <Navigation />
    </div>
  );
};

export default ChatbotPage;


